---
title: "Ingresos y Gastos de los Hogares Ecuatorianos"
subtitle: "Encuesta Nacional de Ingresos y Gastos de los Hogares Urbanos y Rurales (ENIGHUR) 2024-2025"
author: "Daniel Sánchez Pazmiño"
date: today
lang: es
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo
execute:
  echo: false
  warning: false
  message: false
---

# outline

1. ingresos
- ingreso, distribucion
  - comparacion enighur antigua
- ingreso, estructura
- comparacion enemdu (oracion)
- gini?, desigualdad.  
2. gastos
- gasto, distribucion por quintil y total
  - - comparacion enighur antigua
- gasto, estructura
 - gasto en comida, en donde es mas caro
 - gasto en vivienda, en donde es mas caro

grafico principal: en que gastan los hogares ecuatorianos? 
  - un sankey
  - un treemap

xq es importante?

- cpi
- inflacion
- entre otros


# La distribución del ingreso de los hogares es prácticamente la misma que hace 12 años, sugiriendo que la desigualdad no ha mejorado

- comparar distribucion
- nota sobre el cpi
- gini y otros indicadores de desigualdad

# regional: region x tiene el mejor ingreso, y tiene el peor

# la distribucion del gasto... 

# Los hogares mas ricos gastan x% mas

# Los hogares ecuatorianos gastan X% en comida, y x% en vivienda. 

# [provincia] la mas cara para comer es la siguiente


